-- AlterTable
ALTER TABLE "Achievements" ALTER COLUMN "title" DROP NOT NULL,
ALTER COLUMN "org" DROP NOT NULL,
ALTER COLUMN "date" DROP NOT NULL,
ALTER COLUMN "description" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Education" ALTER COLUMN "instituteName" DROP NOT NULL,
ALTER COLUMN "startDate" DROP NOT NULL,
ALTER COLUMN "endDate" DROP NOT NULL,
ALTER COLUMN "location" DROP NOT NULL,
ALTER COLUMN "degree" DROP NOT NULL,
ALTER COLUMN "branch" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Experience" ALTER COLUMN "companyName" DROP NOT NULL,
ALTER COLUMN "startDate" DROP NOT NULL,
ALTER COLUMN "endDate" DROP NOT NULL,
ALTER COLUMN "position" DROP NOT NULL,
ALTER COLUMN "description" DROP NOT NULL,
ALTER COLUMN "proofLink" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Por" ALTER COLUMN "title" DROP NOT NULL,
ALTER COLUMN "org" DROP NOT NULL,
ALTER COLUMN "startDate" DROP NOT NULL,
ALTER COLUMN "endDate" DROP NOT NULL,
ALTER COLUMN "description" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Projects" ALTER COLUMN "projectName" DROP NOT NULL,
ALTER COLUMN "description" DROP NOT NULL,
ALTER COLUMN "githubLink" DROP NOT NULL,
ALTER COLUMN "liveLink" DROP NOT NULL,
ALTER COLUMN "startDate" DROP NOT NULL,
ALTER COLUMN "endDate" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Publications" ALTER COLUMN "authors" DROP NOT NULL,
ALTER COLUMN "title" DROP NOT NULL,
ALTER COLUMN "conference" DROP NOT NULL,
ALTER COLUMN "place" DROP NOT NULL,
ALTER COLUMN "publicationDate" DROP NOT NULL,
ALTER COLUMN "description" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Resume" ADD COLUMN     "name" TEXT NOT NULL DEFAULT 'Resume-1',
ALTER COLUMN "title" DROP NOT NULL,
ALTER COLUMN "summary" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Skills" ALTER COLUMN "name" DROP NOT NULL;
